site: P44N1C0
title: P44N1C0 - Independent Research
description: >
  just a minimalist, personal blog
keywords: Kevin Kusy, Security Researcher, Independent, Vulnerability Researcher, Pentester, Bug Bounty Hunter
googlewebfonts: Fira+Code:wght@400;500;700
repo: https://github.com/p44n1c0/p44n1c0.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: p44n1c0
  username: p44n1c0 # general username
  github: p44n1c0 # github username
  twitter: kevi0x6e # twitter username
  email: kevinnk16@gmail.com # email adress

# URL settings
url: "https://p44n1c0.github.io" #
baseurl: "" # leave blank if not wishd
permalink: "p44n1c0.github.io"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


